version: '3'
services:
  web:
    # ğŸ‘‡ å¯¹åº”ä½  GitHub Action é‡Œçš„ tags
    image: 18879011721/next-ssr-app:latest
    container_name: next-ssr-server
    restart: always
    ports:
      # âœ… å·¦è¾¹æ˜¯æœåŠ¡å™¨ç«¯å£ï¼Œå³è¾¹æ˜¯å®¹å™¨ç«¯å£ (éƒ½åœ¨ Dockerfile é‡Œå®šæ­»äº† 4007)
      - '4007:4007'
    environment:
      - TZ=Asia/Shanghai
