version: '3'
services:
  deeplink-monitor:
    image: 18879011721/next-ssr-app:latest
    container_name: next-ssr-server
    restart: always
    # ❌ 删除 ports 映射
    # ports:
    #   - "4007:4007"

    # ✅ 加上这一行，直接使用宿主机网络
    network_mode: 'host'

    environment:
      - TZ=Asia/Shanghai
      # ✅ 现在你可以直接用 localhost 了！
      - MONGODB_URI=mongodb://localhost:27017/deeplink-monitor
