version: '3'
services:
  web:
    image: your-dockerhub-name/next-ssr-app:latest
    container_name: next-ssr-server
    restart: always
    ports:
      # ✅ 内外都用 4007，清晰明了
      - '4007:4007'
    environment:
      - TZ=Asia/Shanghai
